#!/bin/bash
# Ye-Bash4 Framework test script

# Script version
YE_BASH4_SCRIPT_VERSION="0.3"

ye_bash4_register_F "YB4_ON" "-f" "--flag-no" "Turn a flag off (by default is on)"
YB4_ON=1

ye_bash4_register_F "YB4_NO" "-n" "--flag-on" "Turn a flag on (by default is off)"
YB4_NO=0

ye_bash4_register_P "YB4_DEFAULT" "-d" "--default" "Set a parameter that has a default value"
YB4_DEFAULT="Default value"

ye_bash4_register_P "YB4_MISSING" "-m" "--missing" "Set a parameter that doesn't have a value"
YB4_MISSING=

ye_bash4_register_C "yb4_action1" "-a" "--action1" "Action1 to be performed"
yb4_action1() {
  echo "Performing action1"
}

ye_bash4_register_C "yb4_action2" "-b" "--action2" "Action2 to be performed"
yb4_action2() {
  echo "Performing action2"
}

ye_bash4_register_C "yb4_action3" "-c" "Action3 to be performed"
yb4_action3() {
  echo "Performing action3"
}

ye_bash4_register_C "yb4_action4" "--action4" "Action4 to be performed"
yb4_action4() {
  echo "Performing action4"
}

ye_bash4_version() {
  echo "Overridden"
  echo "$YE_BASH4_SCRIPT_NAME v$YE_BASH4_SCRIPT_VERSION"
  echo
}